"""Strategy Wrapper — Generates MQL5 Expert Advisor code.

Generates a signal-following EA that:
1. Reads trading signals from a shared JSONL file
2. Executes trades via MT5's Strategy Tester engine
3. Logs all execution details for Python-side parsing

The EA is intentionally generic — it doesn't contain any trading logic.
All decisions come from the Python models via the signal file.
"""
import os
import json
from datetime import datetime
from typing import Optional


# MQL5 EA template — a generic signal follower
EA_TEMPLATE = '''//+------------------------------------------------------------------+
//|                                          {ea_name}.mq5           |
//|                          Signal Follower EA for Strategy Tester    |
//|                          Generated by chain_gambler Bridge          |
//+------------------------------------------------------------------+
#property copyright "chain_gambler"
#property version   "1.00"
#property description "Generic signal follower EA - reads signals from Python bridge"

#include <Trade\\Trade.mqh>

input string   SignalFile    = "{signal_file}";  // Path to signal file
input double   LotSize      = {lot_size};        // Default lot size
input int      MagicNumber  = {magic_number};    // EA magic number
input double   MaxSlippage  = {max_slippage};    // Max slippage in points
input double   SpreadLimit   = {spread_limit};    // Max spread in points (0=no limit)

CTrade trade;
datetime lastBarTime = 0;
int signalFileHandle = INVALID_HANDLE;

//+------------------------------------------------------------------+
//| Expert initialization function                                     |
//+------------------------------------------------------------------+
int OnInit()
{{
   trade.SetExpertMagicNumber(MagicNumber);
   trade.SetDeviationInPoints((ulong)MaxSlippage);

   // Try to open signal file for reading
   signalFileHandle = FileOpen(SignalFile, FILE_READ|FILE_TXT|FILE_ANSI);
   if(signalFileHandle != INVALID_HANDLE)
   {{
      Print("Signal file opened: ", SignalFile);
      FileClose(signalFileHandle);
   }}
   else
      Print("Signal file not found (will retry on each tick): ", SignalFile);

   return(INIT_SUCCEEDED);
}}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                   |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{{
   if(signalFileHandle != INVALID_HANDLE)
      FileClose(signalFileHandle);
}}

//+------------------------------------------------------------------+
//| Expert tick function                                               |
//+------------------------------------------------------------------+
void OnTick()
{{
   // Only process once per bar
   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentBarTime == lastBarTime) return;
   lastBarTime = currentBarTime;

   // Read latest signal
   string signal = ReadLatestSignal();
   if(signal == "")
      return;

   // Parse signal JSON
   // Expected format: {{"action":"BUY"|"SELL"|"HOLD"|"CLOSE",
   //                    "symbol":"EURUSDm", "lots":0.01,
   //                    "sl":1.1234, "tp":1.1290}}

   ProcessSignal(signal);
}}

//+------------------------------------------------------------------+
//| Read latest signal from bridge file                                |
//+------------------------------------------------------------------+
string ReadLatestSignal()
{{
   string result = "";

   int handle = FileOpen(SignalFile, FILE_READ|FILE_TXT|FILE_ANSI);
   if(handle == INVALID_HANDLE)
      return "";

   // Read last line (latest signal)
   string line = "";
   while(!FileIsEnding(handle))
   {{
      string current = FileReadString(handle);
      if(current != "")
         line = current;
   }}
   FileClose(handle);

   if(line != "")
   {{
      // Validate JSON
      if(StringFind(line, "{{") >= 0 && StringFind(line, "}}") >= 0)
         result = line;
   }}

   return result;
}}

//+------------------------------------------------------------------+
//| Process trading signal                                             |
//+------------------------------------------------------------------+
void ProcessSignal(string signalJson)
{{
   // Simple JSON parsing (MQL5 has limited JSON support)
   string action = JsonGetString(signalJson, "action");
   double lots   = JsonGetDouble(signalJson, "lots", LotSize);
   double sl     = JsonGetDouble(signalJson, "sl", 0);
   double tp     = JsonGetDouble(signalJson, "tp", 0);

   // Spread check
   if(SpreadLimit > 0)
   {{
      double currentSpread = Ask - Bid;
      int spreadPoints = (int)((currentSpread / _Point) + 0.5);
      if(spreadPoints > (int)SpreadLimit)
      {{
         Print("Spread too wide: ", spreadPoints, " > ", (int)SpreadLimit, " - skipping");
         return;
      }}
   }}

   if(action == "BUY")
   {{
      // Close any existing SELL positions first
      ClosePositions(POSITION_TYPE_SELL);

      // Open BUY
      double askPrice = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double slPrice = (sl > 0) ? sl : 0;
      double tpPrice = (tp > 0) ? tp : 0;

      if(trade.Buy(lots, _Symbol, askPrice, slPrice, tpPrice, "bridge_buy"))
         Print("BUY opened: ", lots, " lots @ ", askPrice, " SL=", slPrice, " TP=", tpPrice);
      else
         Print("BUY failed: ", trade.ResultRetcodeDescription());
   }}
   else if(action == "SELL")
   {{
      // Close any existing BUY positions first
      ClosePositions(POSITION_TYPE_BUY);

      // Open SELL
      double bidPrice = SymbolInfoDouble(_Symbol, SYMBOL_BID);
      double slPrice = (sl > 0) ? sl : 0;
      double tpPrice = (tp > 0) ? tp : 0;

      if(trade.Sell(lots, _Symbol, bidPrice, slPrice, tpPrice, "bridge_sell"))
         Print("SELL opened: ", lots, " lots @ ", bidPrice, " SL=", slPrice, " TP=", tpPrice);
      else
         Print("SELL failed: ", trade.ResultRetcodeDescription());
   }}
   else if(action == "CLOSE")
   {{
      ClosePositions(POSITION_TYPE_BUY);
      ClosePositions(POSITION_TYPE_SELL);
   }}
   // HOLD = do nothing
}}

//+------------------------------------------------------------------+
//| Close all positions of given type                                  |
//+------------------------------------------------------------------+
void ClosePositions(ENUM_POSITION_TYPE posType)
{{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;

      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetInteger(POSITION_TYPE) != posType) continue;

      trade.PositionClose(ticket);
   }}
}}

//+------------------------------------------------------------------+
//| Simple JSON string extraction (MQL5 has no native JSON parser)    |
//+------------------------------------------------------------------+
string JsonGetString(string json, string key)
{{
   string searchKey = "\\"" + key + "\\"": \\"";
   int start = StringFind(json, searchKey);
   if(start < 0) return "";
   start += StringLen(searchKey);
   int end = StringFind(json, "\\"", start);
   if(end < 0) return "";
   return StringSubstr(json, start, end - start);
}}

double JsonGetDouble(string json, string key, double defaultVal)
{{
   string searchKey = "\\"" + key + "\\": ";
   int start = StringFind(json, searchKey);
   if(start < 0) return defaultVal;
   start += StringLen(searchKey);

   // Find end of number
   int end = start;
   while(end < StringLen(json))
   {{
      ushort ch = StringGetCharacter(json, end);
      if(ch == ',' || ch == '}}' || ch == ' ' || ch == '\\n')
         break;
      end++;
   }}

   string numStr = StringSubstr(json, start, end - start);
   double result = StringToDouble(numStr);
   return (result != 0) ? result : defaultVal;
}}
'''


def generate_ea(model, symbol: str, output_dir: str,
                config_overrides: dict = None,
                lot_size: float = 0.01,
                magic_number: int = 505,
                max_slippage: int = 10,
                spread_limit: int = 50) -> str:
    """Generate a signal-following Expert Advisor.

    Args:
        model: Trading model (not directly used — signals come via file)
        symbol: Trading symbol
        output_dir: Directory for EA source and signal files
        config_overrides: Optional config overrides
        lot_size: Default lot size
        magic_number: EA magic number
        max_slippage: Max slippage in points
        spread_limit: Max spread in points

    Returns:
        Path to generated .mq5 file
    """
    os.makedirs(output_dir, exist_ok=True)

    # Signal file path (shared between Python and MQL5)
    signal_file = f"bridge_signals_{symbol}.jsonl"
    signal_path = os.path.join(output_dir, signal_file)

    # Create empty signal file
    with open(signal_path, "w") as f:
        f.write("")

    ea_name = f"ChainGambler_{symbol}"

    ea_code = EA_TEMPLATE.format(
        ea_name=ea_name,
        signal_file=signal_file,
        lot_size=lot_size,
        magic_number=magic_number,
        max_slippage=max_slippage,
        spread_limit=spread_limit,
    )

    ea_path = os.path.join(output_dir, f"{ea_name}.mq5")
    with open(ea_path, "w", encoding="utf-8") as f:
        f.write(ea_code)

    return ea_path


def write_signal(signal_file: str, action: str, symbol: str,
                lots: float, sl: float = 0, tp: float = 0) -> None:
    """Write a trading signal to the bridge signal file.

    This is called from Python to send a signal that the MQL5 EA will read.
    """
    signal = {
        "timestamp": datetime.utcnow().isoformat(),
        "action": action,
        "symbol": symbol,
        "lots": lots,
        "sl": sl,
        "tp": tp,
    }
    with open(signal_file, "a") as f:
        f.write(json.dumps(signal) + "\n")